/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package S3_2n3DependencyInjection;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
